apiVersion: beta/v1
kind: Diamond

metadata:
  name: erc3643-diamond
  version: 1.0.0

spec:
  deployer:
    wallet:
      type: privateKey
      value: "${DEPLOYER_PRIVATE_KEY}"

  diamond:
    name: ERC3643Diamond
    constructorArguments:
      - "0x28F45B9d6b14bC71702e9B268f841B53114BBfA3" # PackageController
      - "0xB0c3D7c364aB389A507040fa81d4C09026262916" # PackageViewer
      - "0xcB44cdc9777bfFd205f10E364EB823379eC5acE4" # InitializablePackage
      - "0xBF368Aa13B1c7be776577F85729ab5DBbd368664" # AgentRole
      - "${ADMIN_ADDRESS}" # Admin address

  packages:
    - name: IdentityRegistry
      functions:
        - "0xa53410dd"
        - "0x653dc9f1"
        - "0x690a49f9"
        - "0x5dbe47e8"
        - "0xa8d29d1d"
        - "0xf0eb5e54"
        - "0xf11abfd8"
        - "0x7e42683b"
        - "0xb9209e33"
        - "0xb4f3fcb7"
        - "0xbf9eb959"
        - "0xe805cf86"
        - "0x9f3418d5"
        - "0x454a03e0"
        - "0xcf191bcd"
        - "0x670af6a9"
        - "0x26d941ae"
        - "0xe744d789"
        - "0x7988d3a5"
        - "0x727e13bc"
        - "0x3b3e12f4"
        - "0x97a012f7"
        - "0x3b239a7f"
        - "0x8e098ca1"
      address: "0x10673825B3BF5197a687F4c476c2115ED7e4A7Eb"
    - name: Compliance
      functions:
        - "0x3ff5aa02"
        - "0xe46638e6"
        - "0x5f8dead3"
        - "0x8d2ea772"
        - "0x6a3edf28"
        - "0x993e8b95"
        - "0x8baf29b4"
        - "0x40db3b50"
      address: "0xDA087f3E9981fe9e957b83EA755416cDE89737e6"
    - name: Token
      functions:
        - "0xdd62ed3e"
        - "0x095ea7b3"
        - "0x70a08231"
        - "0x4a6cc677"
        - "0x42a47abc"
        - "0xfc7e5fa8"
        - "0x68573107"
        - "0x1a7af379"
        - "0x88d695b2"
        - "0x4710362d"
        - "0x9dc29fac"
        - "0x6290865d"
        - "0x313ce567"
        - "0x9fc1d0e7"
        - "0x125c4a33"
        - "0x158b1a57"
        - "0x134e18f4"
        - "0xe5839836"
        - "0x40c10f19"
        - "0x06fdde03"
        - "0xaba63705"
        - "0x8456cb59"
        - "0x5c975abb"
        - "0x9285948a"
        - "0xc69c09cf"
        - "0xf8981789"
        - "0xcbf3f861"
        - "0xc47f0027"
        - "0x3d1ddc5b"
        - "0xb84c8246"
        - "0x95d89b41"
        - "0x18160ddd"
        - "0xa9059cbb"
        - "0x23b872dd"
        - "0x1fe56f7d"
        - "0x3f4ba83a"
        - "0x54fd4d50"
      address: "0xc7251Cd74fCea32cf5c18eE4bfCaf2f2CCf3032C"
    - name: BondManagement
      functions:
        - "0x3fb3ff11" # calculateAccruedInterest()
        - "0x96d6b995" # calculateInvestorAccruedInterest(address)
        - "0x7193ed8f" # calculateOutstandingAmount()
        - "0x20357825" # getTermSheet()
        - "0xecaa0600" # initializeBondToken(string,string)
        - "0x7f2b6a0d" # isMatured()
        - "0x6b5a7fde" # issueBond(address,uint256)
        - "0xa15a211c" # payInterest()
        - "0x68f80376" # payInvestorInterest(address)
        - "0xda781cc5" # redeemAtMaturity()
        - "0xd37633db" # redeemBond(address)
        - "0xc1fdfd2f" # setTermSheet(uint256,uint256,uint256,uint256,uint256)
      address: "0x4E9292446992bbb4FfE0db206895A83e64D90Fd0" # BondManagement contract address

  network:
    chainId: "11155111"
    rpcUrl: "https://sepolia.drpc.org"
