apiVersion: beta/v1
kind: Deployment

metadata:
  name: erc3643-initializable-package-deployment
  version: 1.0.0
  description: 'InitializablePackage deployment for ERC3643'

spec:
  package:
    name: InitializablePackage

  deployer:
    wallet:
      type: 'privateKey' # Options: privateKey, mnemonic, keystore
      value: '${PRIVATE_KEY}' # Environment variable reference

  network:
    chainId: '${CHAIN_ID}'
    rpcUrl: '${RPC_URL}'